-- ORDER created_at
ALTER TABLE `order`
MODIFY COLUMN created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE message
MODIFY COLUMN timestamp TIMESTAMP
DEFAULT CURRENT_TIMESTAMP;

-- ORDER COMPLAINT timestamp
ALTER TABLE order_complaint
MODIFY COLUMN timestamp TIMESTAMP
DEFAULT CURRENT_TIMESTAMP;
--ITEM PHOTO id autoincrement
ALTER TABLE item_photo
MODIFY COLUMN iditem_photo INT NOT NULL AUTO_INCREMENT;
--item review add timestamp column
ALTER TABLE item_review
ADD COLUMN timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE photo
MODIFY COLUMN id_photo INT NOT NULL AUTO_INCREMENT;

ALTER TABLE project_comment
ADD COLUMN timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
