-- ORDER created_at
ALTER TABLE `order`
MODIFY COLUMN created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE message
MODIFY COLUMN timestamp TIMESTAMP
DEFAULT CURRENT_TIMESTAMP;

-- ORDER COMPLAINT timestamp
ALTER TABLE order_complaint
MODIFY COLUMN timestamp TIMESTAMP
DEFAULT CURRENT_TIMESTAMP;