
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_SAFE_UPDATES = 0;

DELETE FROM client;
DELETE FROM employee;
DELETE FROM supervisor;
DELETE FROM user;

ALTER TABLE user AUTO_INCREMENT = 1;
ALTER TABLE supervisor AUTO_INCREMENT = 1;
ALTER TABLE client AUTO_INCREMENT = 1;
ALTER TABLE employee AUTO_INCREMENT = 1;


SET FOREIGN_KEY_CHECKS = 1;
SET SQL_SAFE_UPDATES = 1;
