-- MySQL Script generated by MySQL Workbench
-- Mon 04 May 2026 06:14:52 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema poolprodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poolprodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poolprodb` DEFAULT CHARACTER SET utf8 ;
USE `poolprodb` ;

-- -----------------------------------------------------
-- Table `poolprodb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`supervisor` (
  `id_supervisor` INT NOT NULL,
  PRIMARY KEY (`id_supervisor`),
  CONSTRAINT `fk_supervisor_user1`
    FOREIGN KEY (`id_supervisor`)
    REFERENCES `poolprodb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`employee` (
  `id_employee` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_employee`),
  CONSTRAINT `fk_employee_user1`
    FOREIGN KEY (`id_employee`)
    REFERENCES `poolprodb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`client` (
  `id_client` INT NOT NULL,
  PRIMARY KEY (`id_client`),
  CONSTRAINT `fk_registered_user1`
    FOREIGN KEY (`id_client`)
    REFERENCES `poolprodb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`project` (
  `id_project` INT NOT NULL AUTO_INCREMENT,
  `is_public` TINYINT NOT NULL DEFAULT 0,
  `id_supervisor` INT NOT NULL,
  `id_client` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `status` ENUM('todo', 'in_progress', 'done', 'cancelled') NOT NULL DEFAULT 'todo',
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `client_review` DECIMAL(10,2) NULL,
  `review_text` TEXT NULL,
  PRIMARY KEY (`id_project`),
  INDEX `fk_project_supervisor1_idx` (`id_supervisor` ASC) VISIBLE,
  INDEX `fk_project_registered1_idx` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_project_supervisor1`
    FOREIGN KEY (`id_supervisor`)
    REFERENCES `poolprodb`.`supervisor` (`id_supervisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_registered1`
    FOREIGN KEY (`id_client`)
    REFERENCES `poolprodb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`task` (
  `id_task` INT NOT NULL AUTO_INCREMENT,
  `id_project` INT NOT NULL,
  `id_employee` INT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `status` ENUM('todo', 'in_progress', 'done', 'cancelled') NOT NULL DEFAULT 'todo',
  `deadline` DATE NULL,
  PRIMARY KEY (`id_task`),
  INDEX `fk_task_project1_idx` (`id_project` ASC) VISIBLE,
  INDEX `fk_task_employee1_idx` (`id_employee` ASC) VISIBLE,
  CONSTRAINT `fk_task_project1`
    FOREIGN KEY (`id_project`)
    REFERENCES `poolprodb`.`project` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_employee1`
    FOREIGN KEY (`id_employee`)
    REFERENCES `poolprodb`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`order` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `total_price` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_client` INT NOT NULL,
  `status` ENUM('pending', 'in_progress', 'completed', 'cancelled') NOT NULL DEFAULT 'pending',
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `fk_order_registered1_idx` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_order_registered1`
    FOREIGN KEY (`id_client`)
    REFERENCES `poolprodb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`cart` (
  `id_cart` INT NOT NULL AUTO_INCREMENT,
  `id_client` INT NOT NULL,
  PRIMARY KEY (`id_cart`),
  INDEX `fk_cart_registered1_idx` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_cart_registered1`
    FOREIGN KEY (`id_client`)
    REFERENCES `poolprodb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`item` (
  `id_item` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_item`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`task_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`task_comment` (
  `id_task_comment` INT NOT NULL AUTO_INCREMENT,
  `id_task` INT NOT NULL,
  `id_reply` INT NULL,
  `content` TEXT NOT NULL,
  `id_user` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_task_comment`),
  INDEX `fk_task_comment_task1_idx` (`id_task` ASC) VISIBLE,
  INDEX `fk_task_comment_task_comment1_idx` (`id_reply` ASC) VISIBLE,
  INDEX `fk_task_comment_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_task_comment_task1`
    FOREIGN KEY (`id_task`)
    REFERENCES `poolprodb`.`task` (`id_task`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_comment_task_comment1`
    FOREIGN KEY (`id_reply`)
    REFERENCES `poolprodb`.`task_comment` (`id_task_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_comment_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `poolprodb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`cart_has_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`cart_has_item` (
  `id_cart` INT NOT NULL,
  `id_item` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_cart`, `id_item`),
  INDEX `fk_cart_has_item_item1_idx` (`id_item` ASC) VISIBLE,
  INDEX `fk_cart_has_item_cart1_idx` (`id_cart` ASC) VISIBLE,
  CONSTRAINT `fk_cart_has_item_cart1`
    FOREIGN KEY (`id_cart`)
    REFERENCES `poolprodb`.`cart` (`id_cart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_has_item_item1`
    FOREIGN KEY (`id_item`)
    REFERENCES `poolprodb`.`item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`order_has_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`order_has_item` (
  `id_order` INT NOT NULL,
  `id_item` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_order`, `id_item`),
  INDEX `fk_order_has_item_item1_idx` (`id_item` ASC) VISIBLE,
  INDEX `fk_order_has_item_order1_idx` (`id_order` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_item_order1`
    FOREIGN KEY (`id_order`)
    REFERENCES `poolprodb`.`order` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_item_item1`
    FOREIGN KEY (`id_item`)
    REFERENCES `poolprodb`.`item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`photo` (
  `id_photo` INT NOT NULL AUTO_INCREMENT,
  `id_task` INT NOT NULL,
  `img` VARCHAR(255) NULL,
  PRIMARY KEY (`id_photo`),
  INDEX `fk_photo_task1_idx` (`id_task` ASC) VISIBLE,
  CONSTRAINT `fk_photo_task1`
    FOREIGN KEY (`id_task`)
    REFERENCES `poolprodb`.`task` (`id_task`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`project_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`project_comment` (
  `id_project_comment` INT NOT NULL AUTO_INCREMENT,
  `id_reply` INT NULL,
  `id_project` INT NOT NULL,
  `content` TEXT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_project_comment`),
  INDEX `fk_task_comment_task_comment1_idx` (`id_reply` ASC) VISIBLE,
  INDEX `fk_project_comment_project1_idx` (`id_project` ASC) VISIBLE,
  INDEX `fk_project_comment_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_task_comment_task_comment10`
    FOREIGN KEY (`id_reply`)
    REFERENCES `poolprodb`.`project_comment` (`id_project_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_comment_project1`
    FOREIGN KEY (`id_project`)
    REFERENCES `poolprodb`.`project` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_comment_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `poolprodb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`item_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`item_comment` (
  `id_item_comment` INT NOT NULL AUTO_INCREMENT,
  `id_reply` INT NULL,
  `id_item` INT NOT NULL,
  `content` TEXT NOT NULL,
  `id_user` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_item_comment`),
  INDEX `fk_task_comment_task_comment1_idx` (`id_reply` ASC) VISIBLE,
  INDEX `fk_item_comment_item1_idx` (`id_item` ASC) VISIBLE,
  INDEX `fk_item_comment_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_task_comment_task_comment11`
    FOREIGN KEY (`id_reply`)
    REFERENCES `poolprodb`.`item_comment` (`id_item_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_comment_item1`
    FOREIGN KEY (`id_item`)
    REFERENCES `poolprodb`.`item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_comment_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `poolprodb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`project_complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`project_complaint` (
  `id_project_complaint` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_project` INT NOT NULL,
  PRIMARY KEY (`id_project_complaint`),
  INDEX `fk_project_complaint_project1_idx` (`id_project` ASC) VISIBLE,
  CONSTRAINT `fk_project_complaint_project1`
    FOREIGN KEY (`id_project`)
    REFERENCES `poolprodb`.`project` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`order_complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`order_complaint` (
  `id_order_complaint` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `order_id_order` INT NOT NULL,
  PRIMARY KEY (`id_order_complaint`),
  INDEX `fk_order_complaint_order1_idx` (`order_id_order` ASC) VISIBLE,
  CONSTRAINT `fk_order_complaint_order1`
    FOREIGN KEY (`order_id_order`)
    REFERENCES `poolprodb`.`order` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`message` (
  `id_message` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_sender` INT NOT NULL,
  `id_receiver` INT NOT NULL,
  PRIMARY KEY (`id_message`),
  INDEX `fk_message_user1_idx` (`id_sender` ASC) VISIBLE,
  INDEX `fk_message_user2_idx` (`id_receiver` ASC) VISIBLE,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`id_sender`)
    REFERENCES `poolprodb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user2`
    FOREIGN KEY (`id_receiver`)
    REFERENCES `poolprodb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`item_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`item_photo` (
  `iditem_photo` INT NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `item_id_item` INT NOT NULL,
  PRIMARY KEY (`iditem_photo`),
  INDEX `fk_item_photo_item1_idx` (`item_id_item` ASC) VISIBLE,
  CONSTRAINT `fk_item_photo_item1`
    FOREIGN KEY (`item_id_item`)
    REFERENCES `poolprodb`.`item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poolprodb`.`item_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poolprodb`.`item_review` (
  `client_id_client` INT NOT NULL,
  `item_id_item` INT NOT NULL,
  `review` DECIMAL(10,2) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`client_id_client`, `item_id_item`),
  INDEX `fk_client_has_item_item1_idx` (`item_id_item` ASC) VISIBLE,
  INDEX `fk_client_has_item_client1_idx` (`client_id_client` ASC) VISIBLE,
  CONSTRAINT `fk_client_has_item_client1`
    FOREIGN KEY (`client_id_client`)
    REFERENCES `poolprodb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_item_item1`
    FOREIGN KEY (`item_id_item`)
    REFERENCES `poolprodb`.`item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
